EVoteSystem/Models/VoteSession.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;
using EVoteSystem.Services;

namespace EVoteSystem.Models
{
    public class VoteSession
    {   
        [Key]
        public int VoteSessionId { get; set; }

        [Display(Name = "توضیحات")]
        public string Description { get; set; }
        
        [Display(Name = "تاریخ ایجاد")]
        public DateTime CreatedAt { get; set; }

        public string Year => CreatedAt.GetCurrentYear();
        
        [Display(Name = "فعال")] 
        public bool IsActive { get; set; }

        public string Status => IsActive ? "فعال" : "بسته شده";

        public ICollection<Candidate> Candidates { get; set; }
        
        public ICollection<Vote> SessionVotes { get; set; }
        
        public VoteSession(string description, string year)
        {
            Description = description;
            CreatedAt = DateTime.UtcNow;
        }

        public VoteSession()
        {
            CreatedAt = DateTime.UtcNow;
        }
    }
}

EVoteSystem/Controllers/CandidateController.cs
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EVoteSystem.Models;
using EVoteSystem.Repositories;
using EVoteSystem.Services;
using EVoteSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EVoteSystem.Controllers
{
    [Authorize(Roles =  ValidRoles.Candidate + "," +  ValidRoles.Deputy + "," + ValidRoles.HeadMaster )]
    public class CandidateController : Controller
    {
        private readonly UserManager<Student> _studentUserManager;
        private readonly ISessionRepository _sessionRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly ICandidateRepository _candidateRepository;

        public CandidateController(UserManager<Student> studentUserManager,
            ISessionRepository sessionRepository,
            IStudentRepository studentRepository,
            ICandidateRepository candidateRepository)
        {
            _studentUserManager = studentUserManager;
            _sessionRepository = sessionRepository;
            _studentRepository = studentRepository;
            _candidateRepository = candidateRepository;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "VoteSession");
            }
            var query = _sessionRepository.Queryable();
            var candidates = await query.Include(x => x.Candidates)
                .ThenInclude(x => x.Student).Select(x => x.Candidates).SingleOrDefaultAsync();
            return View(candidates);
        }

        [Authorize(Roles = ValidRoles.Deputy + "," + ValidRoles.HeadMaster)]
        [HttpGet]
        public async Task<IActionResult> AddCandidate()
        {
            var sessions = await _sessionRepository.GetActiveSessions();
            return View("SelectSession", sessions);
        }
        
        [Authorize(Roles = ValidRoles.Deputy + "," + ValidRoles.HeadMaster)]
        [HttpGet("[controller]/[action]/{studentId:int}/{sessionId:int}")]
        public async Task<IActionResult> AddCandidate(int studentId, int sessionId)
        {
            var student = await _studentRepository.FindStudentByIdAsync(studentId);
            return View(student);
        }

        [Authorize(Roles = ValidRoles.Deputy + "," + ValidRoles.HeadMaster)]
        [HttpPost("[controller]/[action]/{studentId:int}/{sessionId:int}"), ActionName("AddCandidate")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCandidateConfirm(int studentId, int sessionId)
        {
            if (ModelState.IsValid)
            {
                var session = await _sessionRepository.FindSessionById(sessionId);
                var student = await _studentRepository.FindStudentByIdAsync(studentId);
                if (session == null || student == null || !session.IsActive)
                {
                    ModelState.AddModelError("","خطا، ورودی ها را کنترل کنید.");
                    return View();
                }
                var candidate = new Candidate()
                {
                    Student = student,
                    Session = session,
                };
                await _candidateRepository.Insert(candidate);
                await _studentUserManager.AddToRoleAsync(student, ValidRoles.Candidate);
                var currentClaim = (await _studentUserManager.GetClaimsAsync(student)).SingleOrDefault(x =>
                    x.Type == "CandidateId");
                if (currentClaim != null)
                {
                    await _studentUserManager.ReplaceClaimAsync(student, currentClaim, new Claim("CandidateId",
                        candidate.CandidateId.ToString()));
                }
                else
                {
                    await _studentUserManager.AddClaimAsync(student,
                        new Claim("CandidateId", candidate.CandidateId.ToString()));
                }

                return RedirectToAction("Index", new {id = sessionId});
            }

            return View();
        }

       
        
        [Authorize(Roles = ValidRoles.Deputy + "," + ValidRoles.HeadMaster)]
        public async Task<IActionResult> RemoveCandidate(int id)
        {
            var candidate = await _candidateRepository.FindCandidateById(id);
            return View(candidate);
        }

        public async Task<IActionResult> RemoveConfirm(int id)
        {
            var candidate = await _candidateRepository.FindCandidateById(id);
            if (candidate != null)
            {
                _candidateRepository.Remove(candidate);
                await _candidateRepository.SaveChangesAsync();
            }

            return RedirectToAction("Index", "VoteSession");
        }

        [HttpGet]
        public async Task<IActionResult> SelectStudent(int id)
        {
            var nonCandidateStudents = await _studentRepository.NotCandidateStudents(id);
            return View(nonCandidateStudents);
        }
    }
}

EVoteSystem/Controllers/VoteSessionController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using EVoteSystem.Models;
using EVoteSystem.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EVoteSystem.Controllers
{
    [Authorize]
    public class VoteSessionController : Controller
    {
        private readonly ISessionRepository _sessionRepository;

        public VoteSessionController(ISessionRepository sessionRepository)
        {
            _sessionRepository = sessionRepository;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var session = await _sessionRepository.GetAll();
            return View(session);
        }

        [HttpGet]
        public IActionResult CreateSession()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSession(VoteSession session)
        {
            if (ModelState.IsValid)
            { 
                session.IsActive = true;
                await _sessionRepository.Insert(session);
               await _sessionRepository.SaveChangesAsync();
               return RedirectToAction("Index");
            }
            ModelState.AddModelError(null, "Please control inputs");
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> CloseSession(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var session = await _sessionRepository.FindSessionById(id);
            if (session == null)
                return RedirectToAction("Index");
            return View(session);
        }

        [HttpPost, ActionName("CloseSession")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CloseSessionConfirm(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var session = await _sessionRepository.FindSessionById(id);
            if (session != null)
            {
                session.IsActive = false;
                _sessionRepository.Update(session);
                await _sessionRepository.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ShowResult(int? id)
        {
            var voteSession = await _sessionRepository.FindSessionById(id);
            var voteCount = voteSession.SessionVotes.Count;
            return null;
        }


        
        
        
        
    }
}

EVoteSystem/Views/VoteSession/CloseSession.cshtml
@model VoteSession

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


<div class="row">
    <div class="col">
        <div class="card card-warning">
            <div class="card-header">
                <h3 class="card-title">آیا از بستن و انتشار نتایج نظرسنجی مطمئن هستید؟</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <div class="card-body">
                <div class="form">
                    <form class="form-validate form-horizontal" id="feedback_form" asp-action="CreateSession">
                        <div class="form-group ">
                            <label asp-for="Description" class="control-label col-lg-2"></label>
                            <div class="col-lg-10">
                                <input class="form-control" asp-for="Description" readonly/>
                            </div>
                        </div>
                        <div class="form-group ">
                            <label asp-for="Year" class="control-label col-lg-2"></label>
                            <div class="col-lg-10">
                                <input class="form-control" asp-for="Year" readonly/>
                            </div>
                        </div>

                        <div class="form-group ">
                            <label asp-for="Description" class="control-label col-lg-2"></label>
                            <div class="col-lg-10">
                                <input class="form-control" asp-for="Status" readonly/>
                            </div>
                        </div>


                       
                    </form>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-warning">ارسال</button>
                    <a class="btn btn-default" type="button" asp-action="Index">برگشت</a>
                </div>

            </div>
        </div>
    </div>

</div>

EVoteSystem/Views/VoteSession/CreateSession.cshtml
@model VoteSession

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


<div class="row">
    <div class="col">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">افزودن فصل جدید</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <div class="card-body">
                <form class="form-validate form-horizontal" id="feedback_form" asp-action="CreateSession">
                    <div class="form-group ">
                        <label asp-for="Description" class="control-label col-lg-2"></label>
                        <div class="col-lg-10">
                            <input class="form-control" asp-for="Description" required/>
                            <span asp-validation-for="Description"></span>
                        </div>
                    </div>
                   
                </form>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">ارسال</button>
                <a class="btn btn-default" type="button" asp-action="Index">برگشتن</a>
            </div>

        </div>
    </div>
</div>

EVoteSystem/Views/VoteSession/Index.cshtml
@model IList<VoteSession>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<a class="btn btn-primary" style="margin-top: 10px; margin-bottom: 10px;" asp-action="CreateSession">افزودن فصل جدید</a>

<div class="row">
    <div class="col">

        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">لیست فصل‌های رای‌گیری</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <div class="card-body">

                <table class="table table-striped table-advance table-hover">
                    <tbody>
                    <tr>
                        <th><i class="icon_profile"></i> توضیحات</th>
                        <th><i class="icon_calendar"></i> سال تحصیلی</th>
                        <th><i class="icon_calendar"></i> وضعیت</th>
                        <th><i class="icon_pencil-edit"></i> عملیات</th>

                    </tr>
                    @foreach (var session in Model)
                    {
                        <tr>
                            <td>@session.Description</td>
                            <td>@session.Year</td>
                            <td>@session.Status</td>
                            <td>
                                @if (session.IsActive)
                                {
                                    <a asp-action="CloseSession" asp-route-id="@session.VoteSessionId" class="btn btn-primary">بستن</a>
                                }
                                else
                                {
                                    <a asp-action="ShowResult" asp-route-id="@session.VoteSessionId" class="btn btn-danger">نتایج</a>
                                }
                                <a asp-action="Index" asp-controller="Candidate" asp-route-id="@session.VoteSessionId" class="btn btn-warning">کاندید‌ها</a>
                            </td>
                        </tr>
                        
                    }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>


    </div>
</div>

EVoteSystem/Views/VoteSession/SessionResult.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}



<div class="row">
    <div class="col">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">مشاهده نتایج برای فصل نظرسنجی</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <div class="card-body">
                
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">ارسال</button>
                <a class="btn btn-default" type="button" asp-action="Index">برگشتن</a>
            </div>

        </div>
    </div>
</div>